name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload files to server
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ftp://yourserver.com
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .
          server-dir: /path/to/your/site
